global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # JMX Exporter가 활성화된 경우 아래 구성 사용
  # - job_name: 'kafka-jmx'
  #   static_configs:
  #     - targets: ['kafka-jmx-exporter:5556'] 